apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {image}
          ports:
            - containerPort: {dockerPort}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {dockerPort}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {hostPort} # internal service port
      targetPort: {dockerPort} # docker port
      nodePort: {hostPort} # node port
